version: "3.3"

services:
  core:
    image: liquidinvestigations/core
    volumes:
      - core-data:/app/var
    ports:
      - 8000:8000

  testapp:
    image: liquidinvestigations/authproxy
    command: ./testapp.py

  testapp-auth:
    image: liquidinvestigations/authproxy
    environment:
      - UPSTREAM_APP_URL=http://testapp:5000
      - LIQUID_INTERNAL_URL=http://core:8000
      - LIQUID_PUBLIC_URL=http://localhost:8000
      - USER_HEADER_TEMPLATE={}
    ports:
      - 5000:5000

volumes:
  core-data:
    driver: local
