---
groups:
- name: prometheus_alerts
  rules:
  - alert: Consul down
    expr: absent(up{job="consul"})
    for: 30s
    labels:
      severity: critical
    annotations:
      description: "Consul is down!"
  - alert: Nomad Server down
    expr: absent(up{job="nomad"})
    for: 30s
    labels:
      severity: critical
    annotations:
      description: "Nomad Server is down!"
  - alert: Nomad Client down
    expr: absent(up{job="nomad-client"})
    for: 30s
    labels:
      severity: critical
    annotations:
      description: "Nomad Client is down!"
  - alert: Vault is down
    expr: absent(up{job="vault"})
    for: 30s
    labels:
      severity: critical
    annotations:
      description: "Vault is down!"
